"use client"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Navbar } from "./components/Navbar"
import "./globals.css"
import { ShoppingCartProvider } from "./context/ShoppingCartContext"
import { Store } from "./components/Store"
import { ShoppingCart } from "./components/ShoppingCart"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  console.log("RootLayout")
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShoppingCartProvider>
          {console.log("StoreStart") ?? null}
          {/* <Navbar></Navbar> */}
          {console.log("RootLayout:Navbar After") ?? null}
          <h1 className="text-3xl">Root Layout:</h1>
          {/* <Store /> */}
          {children}
          {/* <ShoppingCart isOpen={true} /> */}
        </ShoppingCartProvider>
      </body>
    </html>
  )
}
